"""fix relationship user and task

Revision ID: 066d5ebb4c75
Revises: 0df4b5feb2e5
Create Date: 2025-12-01 17:33:13.161266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066d5ebb4c75'
down_revision: Union[str, Sequence[str], None] = '0df4b5feb2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'create_at')
    # ### end Alembic commands ###
