"""fix relationship user and task

Revision ID: 0df4b5feb2e5
Revises: b3f7582ec5cf
Create Date: 2025-12-01 17:31:38.598945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df4b5feb2e5'
down_revision: Union[str, Sequence[str], None] = 'b3f7582ec5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
