"""fix column name

Revision ID: 4fbc16fa32f7
Revises: 066d5ebb4c75
Create Date: 2025-12-08 11:56:03.073121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbc16fa32f7'
down_revision: Union[str, Sequence[str], None] = '066d5ebb4c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('projects_cretor_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'cretor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cretor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_cretor_id_fkey'), 'projects', 'users', ['cretor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'creator_id')
    # ### end Alembic commands ###
