"""database 2.0 with roles and permission

Revision ID: 96259c9e7763
Revises: 4fbc16fa32f7
Create Date: 2025-12-08 17:36:41.421767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96259c9e7763'
down_revision: Union[str, Sequence[str], None] = '4fbc16fa32f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_members_role_id_fkey'), 'project_members', type_='foreignkey')
    op.drop_column('project_members', 'role_id')
    op.drop_constraint(op.f('roles_project_id_fkey'), 'roles', type_='foreignkey')
    op.drop_column('roles', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('roles_project_id_fkey'), 'roles', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('project_members', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('project_members_role_id_fkey'), 'project_members', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
